spring:
  application:
    name: springprj
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        web-allow-others: true

  datasource:
    url: jdbc:h2:./blogdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9000